permissions:
  contents: read
  packages: write

name: BlueBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Debug Cosign secrets
        run: |
          if [ -z "$SIGNING_SECRET" ]; then
            echo "SIGNING_SECRET is EMPTY"
          else
            echo "SIGNING_SECRET length: ${#SIGNING_SECRET}"
          fi

          if [ -z "$COSIGN_PRIVATE_KEY" ]; then
            echo "COSIGN_PRIVATE_KEY is EMPTY"
          else
            echo "COSIGN_PRIVATE_KEY length: ${#COSIGN_PRIVATE_KEY}"
          fi
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Write cosign.key from secret
        run: echo "$COSIGN_PRIVATE_KEY" > cosign.key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: BlueBuild
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

  build-iso:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Login to GHCR
        uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Generate ISO
        uses: jasonn3/build-container-installer@v1.4.0
        with:
          image_name: astral-os_alpha
          image_repo: ghcr.io/masterionio
          image_tag: astral-alpha-v1.00
          iso_name: astral-os_alpha.iso
          variant: COSMIC
          version: 44
          web_ui: false
          image_signed: true
          secure_boot_key_url: https://github.com/Masterionio/astral-os/raw/main/cosign.pub
          enrollment_password: AstralOS777!
          enable_cache_dnf: true
          enable_cache_skopeo: true

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: astral-os_alpha
          path: ./*.iso

  fallback-build-iso:
    runs-on: ubuntu-latest
    needs: build-iso
    if: failure() && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Login to GHCR with PAT
        uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: masterionio
          password: ${{ secrets.PAT }}

      - name: Generate ISO
        uses: jasonn3/build-container-installer@v1.4.0
        with:
          image_name: astral-os_alpha
          image_repo: ghcr.io/masterionio
          image_tag: astral-alpha-v1.00
          iso_name: astral-os_alpha.iso
          variant: COSMIC
          version: 44
          web_ui: false
          image_signed: true
          secure_boot_key_url: https://github.com/Masterionio/astral-os/raw/main/cosign.pub
          enrollment_password: AstralOS777!
          enable_cache_dnf: true
          enable_cache_skopeo: true

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: astral-os_alpha
          path: ./*.iso
